version: '3.3'
services:
  ### postgres container
  cabelusqa-postgres:
    image: postgres
    container_name: cabelusqa-postgres
    ports:
      - "5434:5432"
    networks:
      - cabelusqa
    volumes:
      - ./postgresqa:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cabelusqa
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=cabelusqa@789
      - TZ=America/Sao_Paulo


  ### pgadmin container
  cabelusqa-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=db@cabelusqa.com.br
      - PGADMIN_DEFAULT_PASSWORD=cabelusqa@789
    depends_on:
      - cabelusqa-postgres
    links:
      - cabelusqa-postgres
    networks:
      - cabelusqa

  cabelusqa-redis:
    image: redis:alpine
    container_name: cabelusqa-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redisqa:/data
    ports:
      - 6381:6379
    networks:
      - cabelusqa

networks:
  cabelusqa:
    driver: bridge
